apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: landing-page-deployment
  labels:
    app: landing-page-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing-page-deployment
  template:
    metadata:
      labels:
        app: landing-page-deployment
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: landing-page-deployment
        image: jasnicahuang/landingpage-stage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: staging
  name: landing-page-service
spec:
  selector:
    app: landing-page-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: staging
  name: landing-page-ingress
spec:
  rules:
  - host: lp-stag.jasnicahuang.xyz
    http:
      paths:
      - backend:
          serviceName: landing-page-service
          servicePort: 80

